import type { Metadata } from 'next'
import Navbar from '../ui/dashboard/navbar/navbar'
import Sidebar from '../ui/dashboard/sidebar/sidebar'
import styles from '../ui/dashboard/dashboard.module.css';

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className={styles.container}>
            <div className={styles.menu}><Sidebar /></div>
            <div className={styles.content}>
                <Navbar />
                {children}
            </div>
        </div>
    )
}
